package com.app.task;

import android.annotation.SuppressLint;
import android.content.Context;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class Utils {

    public static String Api_Token ="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLeUEwTl9RYXA0dk5mcTZvQUdnZ05HUDZ6YjhpYkRSMmtMSUE2dXRjWEZvIn0.eyJleHAiOjE2MzE0NDcwNzUsImlhdCI6MTYyOTE3OTM2MCwiYXV0aF90aW1lIjoxNjI4ODU1MDc1LCJqdGkiOiIxNzliOTBhYS03YjViLTQ1ZDEtOTJjNS1hNWUwZDk1NmJmZTYiLCJpc3MiOiJodHRwczovL3Nzby5kZXYubGVhZ3Vlcy5haS9hdXRoL3JlYWxtcy9vcmd1MSIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiI4N2M0MGYxYy00OTJjLTQ5ZDEtODFmMi0wMjFjZjU1MzczNTAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJjaGF0X3dlYl9hcHAiLCJub25jZSI6ImE2MmQ3ZWE1LTQzNTQtNGFlNy1iNzAyLTI1Zjg2NzcyNTUxZCIsInNlc3Npb25fc3RhdGUiOiI3NjY5YjM4NC04ZTM5LTRjYWItYTk0Yi03MTIzZjg5MTYxN2EiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm1hbmFnZV9mZWF0dXJlZF9wb3N0cyIsIm1hbmFnZV9lbXBsb3llZXMiLCJtYW5hZ2VfbGVhcm5pbmdfY29udGVudCIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IlByYXZlZW4gS2F2YWxhZGFuZGkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJvcmd1MS45MTc3NTg4Mzg4MjIiLCJnaXZlbl9uYW1lIjoiUHJhdmVlbiBLYXZhbGFkYW5kaSIsImVtYWlsIjoicHJhdmVlbi5rQGludmVudGUuaW8ifQ.eUdrMJzp_ruiGn9OTq4f6Q7Aw6ttAYegyzOnfJvwgYukOdGVvooBV94SvGohBerCbAf2Y5x_A6zyQmZA9p2H7BPmJARruXrpCmRE6mPREZjLZxct-78aF3Nqq13hyVeBePBakqS6wLu73kJjhx-hpe4tOMVl1bRKQ79rIUBd3MDehdGVqpiEAizrRAwvDKOeNFdxgLX22MLu9onBOhflp2F6vQpGM11OJPf--MsiZJcS0DYGFMswl3Gc3_Zb_Oc6jQa3p04nP_az33lx_ePyYto0pQ_6V-7-1UXGgdVnlcQda6ISCEVUficStpxhPyq1nzet9NBdNYO-c26zvgjuAw";

    public static boolean isNetworkConnectionAvailable(Context context)
    {
        ConnectivityManager cm = (ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);
        @SuppressLint("MissingPermission") NetworkInfo info       = cm.getActiveNetworkInfo();
        if (info == null) return false;
        NetworkInfo.State network   = info.getState();
        return (network == NetworkInfo.State.CONNECTED || network == NetworkInfo.State.CONNECTING);
    }

}
